### ISSUE TITLE
couldn't convert the error to `loco_rs::Error`

### ISSUE THREAD

**Issue by broosk1993** [loco-rs/loco-openapi-Initializer#26]
Hello,

When setting up this crate in a loco-rs project, compilation fails.

### Steps to reproduce:

1. In a fresh loco-rs project, add the following to Cargo.toml:

`loco-openapi = { version = "0.1.0", features = [
    "full",
], git = "https://github.com/loco-rs/loco-openapi-Initializer", branch = "main" }`

2. Add the following to config/development.yaml:

```
initializers:
  openapi:
    redoc:
      url: /redoc
      # spec_json_url: /redoc/openapi.json
      # spec_yaml_url: /redoc/openapi.yaml
    scalar:
      url: /scalar
      # spec_json_url: /scalar/openapi.json
      # spec_yaml_url: /scalar/openapi.yaml
    swagger:
      url: /swagger
      spec_json_url: /api-docs/openapi.json # spec_json_url is required for swagger-ui
      # spec_yaml_url: /api-docs/openapi.yaml
```

3. In app.rs, replace `async fn initializers() with the following:

```
async fn initializers(ctx: &AppContext) -> Result<Vec<Box<dyn Initializer>>> {
        Ok(vec![Box::new(
            loco_openapi::OpenapiInitializerWithSetup::new(
                |ctx| {
                    #[derive(OpenApi)]
                    #[openapi(
                        modifiers(&SecurityAddon),
                        info(
                            title = "Loco Demo",
                            description = "This app is a kitchensink for various capabilities and examples of the [Loco](https://loco.rs) project."
                        )
                    )]
                    struct ApiDoc;
                    set_jwt_location(ctx.into());
    
                    ApiDoc::openapi()
                },
                // When using automatic schema collection only
                None,
                // When using manual schema collection
                // Manual schema collection can also be used at the same time as automatic schema collection
                // Some(vec![controllers::album::api_routes()]),
            ),
        )])
    }
```

4. Run `cargo build`

### The error

I get this error when building the app:

```
cargo build
   Compiling loco-openapi v0.1.0 (https://github.com/loco-rs/loco-openapi-Initializer?branch=main#4b6769b7)
error[E0277]: `?` couldn't convert the error to `loco_rs::Error`
  --> /home/brusk/.cargo/git/checkouts/loco-openapi-initializer-ef977696e1eaeee8/4b6769b/src/utils.rs:36:47
   |
36 |     format::yaml(&get_openapi_spec().to_yaml()?)
   |                                               ^ the trait `From<serde_norway::error::Error>` is not implemented for `loco_rs::Error`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following other types implement trait `From<T>`:
             `loco_rs::Error` implements `From<Box<dyn StdError + Send + Sync>>`
             `loco_rs::Error` implements `From<CacheError>`
             `loco_rs::Error` implements `From<FormRejection>`
             `loco_rs::Error` implements `From<StorageError>`
             `loco_rs::Error` implements `From<ValidationErrors>`
             `loco_rs::Error` implements `From<VarError>`
             `loco_rs::Error` implements `From<axum::extract::rejection::JsonRejection>`
             `loco_rs::Error` implements `From<axum::http::Error>`
           and 15 others
   = note: required for `std::result::Result<axum::http::Response<Body>, loco_rs::Error>` to implement `FromResidual<std::result::Result<Infallible, serde_norway::error::Error>>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `loco-openapi` (lib) due to 1 previous error
```
